In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset=pd.read_csv('insurance_pre.csv')

In [4]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [6]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]

In [9]:
dependent=dataset[['charges']]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
                         

In [12]:
X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [13]:
X_test

array([[ 0.89108031, -0.07576237, -0.0755796 ,  1.01127431, -0.49929923],
       [ 0.5336223 , -0.21009861, -0.0755796 , -0.98885138, -0.49929923],
       [ 0.6051139 ,  1.60182214,  0.75672907,  1.01127431,  2.00280702],
       ...,
       [-1.46814257,  0.65256665,  0.75672907, -0.98885138,  2.00280702],
       [-0.82471815,  0.37742013,  1.58903774,  1.01127431, -0.49929923],
       [ 0.89108031,  1.24817794,  0.75672907, -0.98885138, -0.49929923]])

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid={'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'C':[100,1000,2000,3000],'gamma':['scale', 'auto']}

grid=GridSearchCV(SVR(),param_grid, refit=True, verbose=3, n_jobs=-1)
            


In [15]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [100, 1000, 2000, 3000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [16]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:


In [17]:
 table=pd.DataFrame.from_dict(re)

In [18]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.058382      0.003801         0.009522        0.001779     100   
1        0.056900      0.009019         0.009007        0.003711     100   
2        0.058336      0.005363         0.032137        0.003855     100   
3        0.068971      0.002572         0.010301        0.005812     100   
4        0.053833      0.006300         0.008844        0.002583     100   
5        0.049027      0.004387         0.011023        0.000945     100   
6        0.052270      0.005006         0.036958        0.002672     100   
7        0.065094      0.002454         0.017823        0.004199     100   
8        0.069947      0.003708         0.006732        0.004648    1000   
9        0.071203      0.008597         0.011192        0.003524    1000   
10       0.077644      0.005785         0.033876        0.003631    1000   
11       0.065207      0.003976         0.016097        0.003701    1000   
12       0.068780      0.007322         0.008814        0.007251    1000   
13       0.077093      0.008422         0.006924        0.004456    1000   
14       0.074292      0.005343         0.033167        0.004598    1000   
15       0.073181      0.008795         0.014444        0.003080    1000   
16       0.090585      0.008938         0.005210        0.002980    2000   
17       0.191106      0.164555         0.010078        0.001417    2000   
18       0.085100      0.002735         0.029324        0.004800    2000   
19       0.077645      0.005425         0.010795        0.002426    2000   
20       0.088808      0.006819         0.010467        0.002275    2000   
21       0.157341      0.059092         0.008095        0.004868    2000   
22       0.087369      0.010239         0.039199        0.009717    2000   
23       0.084000      0.006772         0.015508        0.005196    2000   
24       0.106851      0.017369         0.008891        0.004591    3000   
25       0.183543      0.051058         0.010186        0.003227    3000   
26       0.098404      0.008279         0.036549        0.005862    3000   
27       0.088613      0.007313         0.014143        0.002055    3000   
28       0.110607      0.019146         0.010215        0.002163    3000   
29       0.263332      0.148226         0.004437        0.004096    3000   
30       0.096880      0.006569         0.031982        0.001895    3000   
31       0.079729      0.007956         0.014088        0.003959    3000   

   param_gamma param_kernel  \
0        scale       linear   
1        scale         poly   
2        scale          rbf   
3        scale      sigmoid   
4         auto       linear   
5         auto         poly   
6         auto          rbf   
7         auto      sigmoid   
8        scale       linear   
9        scale         poly   
10       scale          rbf   
11       scale      sigmoid   
12        auto       linear   
13        auto         poly   
14        auto          rbf   
15        auto      sigmoid   
16       scale       linear   
17       scale         poly   
18       scale          rbf   
19       scale      sigmoid   
20        auto       linear   
21        auto         poly   
22        auto          rbf   
23        auto      sigmoid   
24       scale       linear   
25       scale         poly   
26       scale          rbf   
27       scale      sigmoid   
28        auto       linear   
29        auto         poly   
30        auto          rbf   
31        auto      sigmoid   

                                               params  split0_test_score  \
0    {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}           0.596232   
1      {'C': 100, 'gamma': 'scale', 'kernel': 'poly'}           0.532310   
2       {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}           0.304939   
3   {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}           0.491855   
4     {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}           0.596232   
5       {'C': 1

In [19]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 29
BMI: 26
Children: 0
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

In [21]:
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3616454.72643123]


In [22]:
import pickle

In [23]:
filename='Final_model_svr.sav'

In [24]:
pickle.dump(grid,open(filename,'wb'))

In [25]:
loaded_model=pickle.load(open('Final_model_svr.sav','rb'))

In [31]:
result=loaded_model.predict([[29,26,0,1,1]])

In [32]:
result

array([3616454.72643123])